services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: handpi-backend
    expose:
      - "5001"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: handpi-frontend
    expose:
      - "80"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: handpi-nginx
    volumes:
      - ./nginx/nginx.production.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    networks:
      - internal
      - global_proxy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend
      - frontend

networks:
  internal:
    driver: bridge
  global_proxy_net:
    external: true