apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: handpi-portfolio-spa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Amirofcodes/HandPi-Games.git
    targetRevision: docs/portfolio-spa
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-spa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
