apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: handpi-games
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Amirofcodes/HandPi-Games.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: handpi-games
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
