apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: handpi-games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
<<<<<<< HEAD
          image: ghcr.io/amirofcodes/handpi-backend:20250530-7df3930
=======
          image: ghcr.io/amirofcodes/handpi-backend:20250530-d4a2d9b
>>>>>>> bdd487e (Fix nginx permission issues and update image tags)
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: handpi-secrets
            - configMapRef:
                name: handpi-config
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: ghcr-cred
