apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: handpi-games
  labels:
    app: handpi
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: handpi
      component: frontend
  template:
    metadata:
      labels:
        app: handpi
        component: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest # Will be replaced by kustomize
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101 # nginx user
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
