apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: handpi-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          image: ghcr.io/amirofcodes/handpi-router:20250530-7df3930
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: router-config
      imagePullSecrets:
        - name: ghcr-cred
