apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: handpi-games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          image: ghcr.io/amirofcodes/handpi-router:20250530-a79244c
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          imagePullPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: router-config
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr-cred
