apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: handpi-games
spec:
  selector:
    app: router
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
