apiVersion: v1
kind: Secret
metadata:
  name: handpi-secrets
  namespace: handpi-games
type: Opaque
stringData:
  SECRET_KEY: "your-production-secret-key"
  JWT_SECRET: "your-production-jwt-secret"
  DATABASE_URL: "postgresql://user:password@postgres:5432/handpi_db"
# Note: This should be converted to a SealedSecret before committing to git
