apiVersion: v1
kind: Secret
metadata:
  name: handpi-secrets
  namespace: handpi-games
type: Opaque
stringData:
  SECRET_KEY: "your-production-secret-key-change-this-in-production"
  FLASK_ENV: "production"
# Note: This should be converted to a SealedSecret before committing to git
